### ISSUE TITLE
Make fused RMSNorm a registered op

### ISSUE THREAD

**Issue by lessw2020** [pytorch/torchtitan#199]
Adding this as tracking issue to unblock https://github.com/pytorch/torchtrain/pull/181 from landing:
per @wanchaol :
IMO we should also register the fwd/bwd rmsnorm kernel as a PyTorch op, this is so that:

making it a custom op makes it compatible with PT2, which I believe it's currently graph breaking on the FusedRMSNorm path if we turn on torch.compile
it allows other components (i.e. DTensor) to provide sharding rule to this custom op so that it would compatible with the tensor parallelism

**Comment by tianyu-l** [comment]
update: Hit IMA issues for both my implementation #296 and @wconstab's #303. Working on debugging with @lessw2020 .

**Comment by tianyu-l** [comment]
closing this as we have supported this fused RMSNorm in Tensor Parallelism (#404).
