### ISSUE TITLE
Question; parallelising convolutional layers?

### ISSUE THREAD

**Issue by jvwilliams23** [pytorch/torchtitan#277]
Hi,

I was wondering, is `torchtitan` and/or `DTensor` capable of model parallel training of convolutional neural network layers? Pretty much, we want to train a GAN on very large 2D images (eventually 3D), so the whole model cannot fit on one GPU. It seems the scope of this is maybe limited to LLMs/transformers, but I wanted to check.

Best,
Josh

**Comment by jvwilliams23** [comment]
Thanks for the link to ConvNeXt!

The model is moderate (around 20M parameters). For large images, we usually use batch size = 1 image.

**Comment by jvwilliams23** [comment]
The DTensor link you shared answers my question, so closing this now.

**Comment by awgu** [comment]
Got it! I think in that case, I agree data parallelism does not make sense, and tensor parallelism is the way to go :)

**Comment by xingchensong** [comment]
> I think `DTensor` has some support for conv ops (but maybe not full coverage). There is an example of training a ConvNeXt model here: https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/examples/convnext_example.py
> 
> > Pretty much, we want to train a GAN on very large 2D images (eventually 3D), so the whole model cannot fit on one GPU.
> 
> To clarify, is the model itself small, but the activation sizes are large due to the image resolution? What is the batch size that you are training with?
> 
> For a fixed global batch size, data parallelism is still a valid way to reduce per-GPU activation size. E.g., if you wanted to train with global batch size of 8 on 8 GPUs, then with tensor parallelism, you would need each of the 8 GPUs to work on the same batch with size 8, whereas with data parallelism, you can just have each GPU work on batch size of 1.
> 
> In that case, using only FSDP (or DDP) may still help you train.

Hello, this link has expired. May I ask if there is a new link that can be used to demonstrate how to perform tp on convolution?

**Comment by tianyu-l** [comment]
@xingchensong here's the example: https://github.com/pytorch/pytorch/blob/main/torch/distributed/tensor/examples/convnext_example.py
