### ISSUE TITLE
lr scheduler - update global states into optimizer

### ISSUE THREAD

**Issue by lessw2020** [pytorch/torchtitan#29]
lr scheduler currently maintains two global states to implement the full lr warmup and decay. 
We want to remove these:
"nit: we can make these two arguments still as function arguments below, but we use:

functools.partial to pack these two arguments when adding to the optimizer.

global config works for now. This can be done as a follow up"

**Comment by awgu** [comment]
cc: @tianyu-l is this issue done?

**Comment by tianyu-l** [comment]
Seems not. @awgu 

> cc: @tianyu-l is this issue done?
