### ISSUE TITLE
RoPE implementation differences

### ISSUE THREAD

**Issue by rlrs** [pytorch/torchtitan#335]
I've been working with the pretrained Llama 3 weights, and found out that the RoPE implementation here does not match the one found in other places. The difference is whether you treat sequential entries of the embeddings as (real, imaginary), or you treat the first half as real, and the second half as imaginary. 

The current torchtitan implementation uses the former, while both Transformers and llama.cpp for example use the latter. 
This also seems to mean that loading weights from https://huggingface.co/meta-llama/Meta-Llama-3-8B does not work. I've verified numerically that you need to use the latter RoPE implementation to get correct results with existing weights. I'm slightly worried that I'm doing something wrong, but perhaps someone else can verify? I can post some code if that helps.

Here's a small change to `apply_rotary_emb` which can be used to make it match the cos/sin implementation numerically.
```python
def apply_rotary_emb(
    xq: torch.Tensor,
    xk: torch.Tensor,
    freqs_cis: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Apply rotary embeddings to input tensors using the given frequency tensor.

    This function applies rotary embeddings to the given query 'xq' and key 'xk' tensors using the provided
    frequency tensor 'freqs_cis'. The input tensors are reshaped as complex numbers, and the frequency tensor
    is reshaped for broadcasting compatibility. The resulting tensors contain rotary embeddings and are
    returned as real tensors.

    Args:
        xq (torch.Tensor): Query tensor to apply rotary embeddings.
        xk (torch.Tensor): Key tensor to apply rotary embeddings.
        freqs_cis (torch.Tensor): Precomputed frequency tensor for complex exponentials.

    Returns:
        Tuple[torch.Tensor, torch.Tensor]: Tuple of modified query tensor and key tensor with rotary embeddings.
    """
    # first half is real, second half is imaginary
    xq_ = torch.complex(xq[..., :xq.shape[-1] // 2].float(), xq[..., xq.shape[-1] // 2:].float())
    xk_ = torch.complex(xk[..., :xk.shape[-1] // 2].float(), xk[..., xk.shape[-1] // 2:].float())
    freqs_cis = reshape_for_broadcast(freqs_cis, xq_)
    xq_out = torch.view_as_real(xq_ * freqs_cis).flatten(3)
    xk_out = torch.view_as_real(xk_ * freqs_cis).flatten(3)
    
    # added this
    xq_out = torch.cat([xq_out[..., ::2], xq_out[..., 1::2]], dim=-1)
    xk_out = torch.cat([xk_out[..., ::2], xk_out[..., 1::2]], dim=-1)
    
    return xq_out.type_as(xq), xk_out.type_as(xk)
```

**Comment by TJ-Solergibert** [comment]
Hi @rlrs ! Could you share the script to transform the weights from HF to dcp? Thanks!

**Comment by tianyu-l** [comment]
Hi @rlrs, thanks for bringing up the concern!

We are using the same definition as in llama3 code https://github.com/meta-llama/llama3/blob/main/llama/model.py#L65
Would you provide more details on how you verified the loaded weights to be wrong / correct?

**Comment by tianyu-l** [comment]
@rlrs
It seems HF's llama implementation is different from the official llama's. We'll need to understand why that's the case.

HF: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L184
meta-llama: https://github.com/meta-llama/llama3/blob/main/llama/model.py#L65

**Comment by rlrs** [comment]
Thanks for asking over there. I didn't try to download the weights from anywhere other than HF, but I would be a bit surprised if there's some simple transformation you can do to the weights to change the rope implementation? 
Anyways let's await some information from their side.

**Comment by rlrs** [comment]
As discussed in the HF issue, there is indeed a permutation of the weights that causes the two implementations to be equivalent. I don't believe anything needs to be done in the torchtitan repo, and if you agree, feel free to close this issue.

**Comment by tianyu-l** [comment]
@rlrs 
> This also seems to mean that loading weights from https://huggingface.co/meta-llama/Meta-Llama-3-8B does not work.

If I understand correctly, there are two ways you can download weights from HF. The first way is from the `original` folder which gives the same weights as downloaded from meta llama website; the second way is through HF api `transformers.pipeline` which probably does the conversion.

I think torchtitan at least should have code & tutorial to load the original weights. For the second, HF should support the conversion from HF transformer to llama weights.
