### ISSUE TITLE
checkpoint.model_weights_only Doesn't makes any difference

### ISSUE THREAD

**Issue by TJ-Solergibert** [pytorch/torchtitan#336]
Hi,

With the llama3-8B config either setting in the .toml file `model_weights_only = true` // `false` or via the `--checkpoint.model_weights_only` flag produces exactly the same checkpoints, same size even across multiple runs.

<img width="435" alt="Screenshot 2024-05-16 at 00 25 46" src="https://github.com/pytorch/torchtitan/assets/74564958/5760559c-21dc-43d3-973b-ad18a64b7eb8">

Also HF Llama3-8B checkpoints are ~16 GB compared to the 90GB it's producing. Running with DP = 4, PP = 1 & TP = 1.

**Comment by fegin** [comment]
`model_weights_only` will only be effect for the very last checkpoint, after all training is done. We could not do `model_weights_only` for all other checkpoints as those checkpoints can also be used for fault tolerance.
