### ISSUE TITLE
Add torchdata to requirements after release

### ISSUE THREAD

**Issue by gokulavasan** [pytorch/torchtitan#351]
Currently the user has to pip install the nightly explicitly. Instead once torchdata is released with StatefulDataLoader, add it to requirements.txt and pyproject.toml and remove the pip install from added in github workflow .yaml files and README Referenced [here](https://github.com/pytorch/torchtitan/pull/279#discussion_r1608909568).

**Comment by tianyu-l** [comment]
ready in https://github.com/pytorch/torchtitan/pull/513
