### ISSUE TITLE
Add tests to test each component

### ISSUE THREAD

**Issue by wanchaol** [pytorch/torchtitan#40]
The tentative tests we could add:
1. test the llama debug model init and forward/backward works
2. test checkpoint save/load works
3. metrics logging test (metrics to be added)

**Comment by tianyu-l** [comment]
TODO: test correctness of checkpointable data loading in #279

**Comment by tianyu-l** [comment]
@wconstab is going to help set up an example multi-gpu unit test. We can add more functionality unit test following the example.
