### ISSUE TITLE
NotImplementedError: aten::nonzero: attempted to run this operator with Meta tensors at loss.backward()

### ISSUE THREAD

**Issue by MinghaoYan** [pytorch/torchtitan#415]
Hi,

I'm trying to implement lora on top of llama, and ran into the following error at the loss.backward() step. The only changes I have made are to replace the attention module with a lora module and freeze llama's original parameters. 

> [rank2]:[rank2]: Traceback (most recent call last):
[rank2]:[rank2]:   File "/home/ubuntu/torchtitan/train.py", line 503, in <module>
[rank2]:[rank2]:     main(config)
[rank2]:[rank2]:   File "/home/ubuntu/.conda/envs/torchtitan/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
[rank2]:[rank2]:     return f(*args, **kwargs)
[rank2]:[rank2]:   File "/home/ubuntu/torchtitan/train.py", line 369, in main
[rank2]:[rank2]:     loss.backward()
[rank2]:[rank2]:   File "/home/ubuntu/.conda/envs/torchtitan/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
[rank2]:[rank2]:     torch.autograd.backward(
[rank2]:[rank2]:   File "/home/ubuntu/.conda/envs/torchtitan/lib/python3.10/site-packages/torch/autograd/__init__.py", line 288, in backward
[rank2]:[rank2]:     _engine_run_backward(
[rank2]:[rank2]:   File "/home/ubuntu/.conda/envs/torchtitan/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
[rank2]:[rank2]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank2]:[rank2]:   File "/home/ubuntu/.conda/envs/torchtitan/lib/python3.10/site-packages/torch/_meta_registrations.py", line 3026, in meta_index_Tensor
[rank2]:[rank2]:     nonzero = index.nonzero()
[rank2]:[rank2]: NotImplementedError: aten::nonzero: attempted to run this operator with Meta tensors, but there was no fake impl or Meta kernel registered. You may have run into this message while using an operator with PT2 compilation APIs (torch.compile/torch.export); in order to use this operator with those APIs you'll need to add a fake impl. Please see the following for next steps:  https://pytorch.org/docs/main/notes/custom_operators.html

I have checked every model parameter as well as gradients, and they are all on device and not metatensors. I have set compile flag to be false and checkpoint to be false in my toml config (same as the config provided in llama3_8b.toml). What else might have caused this error? 

My Pytorch version is the latest 2.5.0 nightly.

**Comment by awgu** [comment]
Would it be possible to share your implementation / your changes?

**Comment by MinghaoYan** [comment]
I ended up rewriting it and the problem is gone. I will close the issue then. Thank you all the same!
