### ISSUE TITLE
improve memory profiler to not to profile every iteration

### ISSUE THREAD

**Issue by tianyu-l** [pytorch/torchtitan#422]
Currently if we enable memory profiling, every iteration will be profiled with trace dumped, regardless of profile frequency. This overhead can be avoided if we only profile and dump one iteration per `profile_freq` steps.

referring to https://github.com/pytorch/torchtitan/pull/395#pullrequestreview-2121075514

**Comment by awgu** [comment]
https://github.com/pytorch/torchtitan/pull/430
