### ISSUE TITLE
what's the est timeline for releasing Context Parallel and 3D Pipeline 

### ISSUE THREAD

**Issue by jason718** [pytorch/torchtitan#478]
Many interesting topics are mentioned in coming soon section, I'm wondering do we have a estimated/targeted releasing date? Thanks again for the great work.

**Comment by tianyu-l** [comment]
Most topics in the "coming soon" are already included in main. We will update the README.

Basic PP is ready and we are still adding more advanced features/variants (e.g. zero-bubble PP).

CP is available in #433. @fegin to share more on progress.

**Comment by jason718** [comment]
Awesome! thx
