### ISSUE TITLE
any plans to add improved PP in llama-3?

### ISSUE THREAD

**Issue by SeunghyunSEO** [pytorch/torchtitan#483]
batch constraint removed Pipeline Parallelism (PP) in llama-3 paper seems to added [torch 2.4](https://pytorch.org/docs/main/distributed.pipelining.html#torch.distributed.pipelining.schedules.ScheduleFlexibleInterleaved1F1B).
do you have any plans to add this feature to torchtitan ?!

**Comment by tianyu-l** [comment]
@wconstab @H-Huang anything to share?

**Comment by H-Huang** [comment]
Hi @SeunghyunSEO, the `ScheduleFlexibleInterleaved1F1B` was not introduced in 2.4, but it is available in the PyTorch nightly build (and will be available in the 2.5 release).

For `torchtitan` I can quickly add a PR to add a flag to support this schedule.

**Comment by H-Huang** [comment]
merged in https://github.com/pytorch/torchtitan/commit/9cf4b2f97ae85bff3b546436be6fd275c25619e7
