### ISSUE TITLE
compiled rms_norm not numerically accurate (fails to produce good loss curves) when run under tp

### ISSUE THREAD

**Issue by lessw2020** [pytorch/torchtitan#497]
When doing large scale runs, found that compiled_rmsnorm was producing aberrant loss curves compared to tp or async tp with rmsnorm.
Verified this reproes with small scale and thus opening issue for tracking. 
Compiled rmsnorm works fine under 1D FSDP. 

Easy repro is to run debug model and 50 steps with compiled rms_norm with tp, vs tp with rms norm:
fsdp + compile + rmsnorm:
<img width="1260" alt="Screenshot 2024-07-31 at 11 51 47 AM" src="https://github.com/user-attachments/assets/94f34ab4-38ad-4e58-957c-ba2ea395b407">

fspd + tp (2) + compile + rmsnorm:
<img width="1260" alt="Screenshot 2024-07-31 at 11 52 26 AM" src="https://github.com/user-attachments/assets/0c0468ac-06a0-43cb-9146-c9c876d5bae3">

 Issue shown here: 
 fsdp + tp(2) + compiled rms norm:
<img width="1260" alt="Screenshot 2024-07-31 at 11 52 09 AM" src="https://github.com/user-attachments/assets/d8c44dd0-b7ea-4a7d-9bf8-571a86f4cb21">

Finally, compiled rmsnorm + fsdp + compile (1D) works fine:
<img width="1260" alt="Screenshot 2024-07-31 at 12 51 24 PM" src="https://github.com/user-attachments/assets/3292d1d8-cb5c-4597-9839-2aeffc214110">

**Comment by tianyu-l** [comment]
I  investigated the issue. Unit test (#506) shows the `compiled_rmsnorm` computation is correct, even with TP / DTensor. Also the first two iterations loss agree with `rmsnorm` when random seed is fixed.

The numerical issue could be due to recompiles with TP, as if I enable `TORCH_LOGS="recompiles"` together with TP, it says:
```
[rank0]:[rank0]:V0805 21:17:40.412000 1216054 torch/_dynamo/guards.py:2687] [0/1] [__recompiles] Recompiling function compute_rmsnorm in /home/lty/torchtitan/torchtitan/models/norms.py:102
[rank0]:[rank0]:V0805 21:17:40.412000 1216054 torch/_dynamo/guards.py:2687] [0/1] [__recompiles]     triggered by the following guard failure(s):
[rank0]:[rank0]:V0805 21:17:40.412000 1216054 torch/_dynamo/guards.py:2687] [0/1] [__recompiles]     - 0/0: ___check_type_id(L['x']._local_tensor, 103225664)
```

Moreover, adjusting `torch._dynamo.config.cache_size_limit` seems affecting the results after the first two iters.

cc: @bdhirsh @wanchaol

**Comment by tianyu-l** [comment]
update: as https://github.com/pytorch/pytorch/pull/124401 landed, there's no longer recompiles but the numerical issue persists, which needs further investigation.

**Comment by tianyu-l** [comment]
close as we've removed this feature
