### ISSUE TITLE
How to calculate the total batchsize

### ISSUE THREAD

**Issue by zyushun** [pytorch/torchtitan#572]
Hi, it is me again~ I have a quick simple question: I am using the following training config with 4 GPUs. What is the total number of tokens per optimizer step? Is it 2 * 2048 or 2 * 2048 * 4?

```
[training]
batch_size = 2
seq_len = 2048 
warmup_steps = 2000  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 10000
data_parallel_degree = -1
tensor_parallel_degree = 1
fp8_linear = ""
compile = false
```

**Comment by fegin** [comment]
You need to multiply the batch_size with the data_parallel_degree. So `2 * 2048 * 4` is what you are looking for.
