### ISSUE TITLE
`max_batch_size` argument in `ModelArgs`

### ISSUE THREAD

**Issue by eminorhan** [pytorch/torchtitan#583]
I'm just curious what the `max_batch_size` argument does in `ModelArgs`: https://github.com/pytorch/torchtitan/blob/d2a4904f58accc683c17c66a360026cb3c8109af/torchtitan/models/llama/model.py#L32

A quick search suggests that it doesn't actually seem to be used anywhere else in the code base, so I'm wondering if it might be superfluous.

**Comment by XilunWu** [comment]
I think this argument currently serve as a placeholder and may be used in future. What do you think? @lessw2020 @tianyu-l

**Comment by awgu** [comment]
I think it was copied from the original reference Llama implementation, which was meant for inference ([code](https://github.com/meta-llama/llama/blob/8fac8befd776bc03242fe7bc2236cdb41b6c609c/llama/model.py#L30)) and the `max_batch_size` was used for the KV cache.

We should probably remove it.

**Comment by XilunWu** [comment]
#585
