### ISSUE TITLE
RoPE Scaling for Llama with FSDP2 and Meta Init

### ISSUE THREAD

**Issue by karan-dalal** [pytorch/torchtitan#612]
Hi. I'm attempting to implement RoPE scaling used in LLaMa 3.1+ (https://github.com/meta-llama/llama-models/blob/373bfad50798519cf88302d1106bae7a0671998b/models/llama3/reference_impl/model.py#L45C1-L67C75) in TorchTitan.

However, due to the meta initialization, I'm unable to correctly handle the comparisons for determining scaling of wave frequencies.

If I simply include:
```python
    if freqs.is_meta:
        return torch.empty_like(freqs, device="meta")
``` 

I won't actually properly use the RoPe scaling (it won't trigger the if statement in `precompute_freqs_cis`). I've found a work around by disabling the persistent register buffer here `self.register_buffer("freqs_cis", self._precompute_freqs_cis(), persistent=False)`, but I notice the comments about incompatibility with PP and compile.

Would there be any other workaround for this function? Thanks!

**Comment by awgu** [comment]
I would first say that if making it a non-persistent buffer works, you should do that. I think `freqs_cis` should be non-persistent morally speaking because it is not meant to be saved to state dict.

**Comment by karan-dalal** [comment]
Ok, thank you for your response!
