### ISSUE TITLE
redundant checks in `checkpoint.py`

### ISSUE THREAD

**Issue by eminorhan** [pytorch/torchtitan#617]
The `assert` statements [here](https://github.com/pytorch/torchtitan/blob/c1343451c2354d8042dc1a2805a291f3dbf84de6/torchtitan/checkpoint.py#L205C1-L210C55) and [here](https://github.com/pytorch/torchtitan/blob/c1343451c2354d8042dc1a2805a291f3dbf84de6/torchtitan/checkpoint.py#L212C1-L217C55) are identical. It seems that that code block was inadvertently copied.

**Comment by tianyu-l** [comment]
fixed in https://github.com/pytorch/torchtitan/pull/657
