### ISSUE TITLE
How to load previous distributed checkpoint after using FP8Linear + torch.compile?

### ISSUE THREAD

**Issue by goldhuang** [pytorch/torchtitan#639]
FP8Linear + torch.compile is changing the parameters's name. 

If I do convert to FP8Linear -> torch.compile -> fsdp2 wrapping -> load distributed ckpt, the parameters's names do not match with the ckpt we want to resume from. And it's not straightforward to change the parameters's names in the distributed ckpt.

Thus, my question is what's the expected solution for this workflow?

Thanks a lot!

**Comment by fegin** [comment]
@weifengpy Is it possible for FP8Linear to keep the FQNs? Otherwise composability can be a problem.

**Comment by goldhuang** [comment]
torch.compile definitely change the parameters's name by adding ._orig_mod. My question is probably not specific to FP8Linear.
I find it very difficult to migrate a distributed ckpt. (It's very easy with full ckpt.) I wonder what's the best practice to leverage with previous distributed ckpt after apply some layer conversions.
Thanks!

**Comment by tianyu-l** [comment]
cc: @weifengpy @wz337

**Comment by fegin** [comment]
@goldhuang Could you tell more about the difficulty? `_orig_mod` should be removed by `distributed state_dict` -- `get_model_state_dict` which is used in TorchTitan. Also if the naming/FQN changes, how can you load full state_dict but not distributed state_dict?

**Comment by goldhuang** [comment]
@fegin I'm using the code below to load a distributed ckpt.
```
state = {"model": model}
path = Path(path)
planner = DefaultLoadPlanner(allow_partial_load=not strict)
torch.distributed.checkpoint.load(state_dict=state, checkpoint_id=path, planner=planner)
```
The parameters's names in the ckpt need to match those in the model.
After I use torchao+torch.compile (or torch.compile only), they do not match with each other.

If it were a full ckpt, I can just load it to a dict and migrate the names. But not sure what's the expected way to use torch.distributed.checkpoint.load for my case.

**Comment by weifengpy** [comment]
> is it possible for FP8Linear to keep the FQNs? Otherwise composability can be a problem.

Catching up on the thread - I believe the focus is more on dealing with `_orig_mod` caused by torch.compile

float8 itself keep fqn unchanged
```
[rank0]:before float8 swapping: ['layers.0.attention.wq.weight']
[rank0]:after float8 swapping: ['layers.0.attention.wq.weight']
```

```
diff --git a/train.py b/train.py
index 3e8994a..cd1341e 100644
--- a/train.py
+++ b/train.py
@@ -128,8 +128,14 @@ def main(job_config: JobConfig):
 
     # a no-op hander if float8 is not enabled
     float8_handler = Float8Handler(job_config, parallel_dims)
+    if torch.distributed.get_rank() == 0:
+        print(f"before float8 swapping: {list(name for name, _ in model.named_parameters())}", flush=True)
     # swap to Float8Linear based on float8 configs
     float8_handler.convert_to_float8_training(model)
+    if torch.distributed.get_rank() == 0:
+        print(f"after float8 swapping: {list(name for name, _ in model.named_parameters())}", flush=True)
+    
+    torch.distributed.breakpoint()
```

**Comment by fegin** [comment]
@goldhuang Looks like your program is not using any of TorchTitan code? If you follow the checkpoint.py logic, `_orig_mod` is not an issue.

**Comment by goldhuang** [comment]
The problem can be solved by get_model_state_dict and set_model_state_dict.
