### ISSUE TITLE
Why use TF32 Tensorcore Peak Flops for MFU calculation?

### ISSUE THREAD

**Issue by LeoXinhaoLee** [pytorch/torchtitan#668]
Hi, thank you for releasing this wonderful codebase.

I noticed that the MFU calculation in your code is using the **TF32 Tensorcore peak FLOPs** as denominator, as hard-coded [here](https://github.com/pytorch/torchtitan/blob/d7cabfb6cc987f9310a4bfa5b87b1dbb8974b10c/torchtitan/utils.py#L211).

However, since FSDP uses `--training.mixed_precision_param`, does that mean the mix-precision training is using BF16 instead, and thus should use the **BF16 Tensorcore** peak FLOPs?

E.g., according to [manual](https://www.nvidia.com/en-us/data-center/h100/?srsltid=AfmBOoob1LDKIiO3iuCm45l_ON_xuwaZEXVeEc9VuK8CpZt4qCtl9bfv) on H100 SXM, the BF16 peak FLOPs is about 2x TF32 peak FLOPs.

Thank you very much for your time and help! @lessw2020

**Comment by lessw2020** [comment]
Hi @LeoXinhaoLee  - wow, good catch!  You are right, we meant to be using BF16 given the default mixed precision, but somehow the TF32 numbers were copied in.
Let me make a PR to correct this, and thanks again for flagging.  
Will update here with the PR shortly.

**Comment by LeoXinhaoLee** [comment]
Thank you for your reply. I'm wondering if the MFUs reported [here](https://github.com/pytorch/torchtitan/blob/main/docs/performance.md) are also calculated with this problem?

**Comment by LeoXinhaoLee** [comment]
It turns out that the BF16 Tensorcore peak FLOPs/s reported on H100 datasheet is with sparsity. It doesn’t say what’s the BF16 peak FLOPs/s. However, on A100, the non-sparsity peak FLOPs/s is 1/2 of sparsity’s. So extrapolating from this relation, the BF16 peak FLOPs/s should be 0.5 * 1,979e12 = 989e12.

Therefore, I think the codebase is calculating MFU correctly (without sparsity). Thank you again for your timely response, and it would be great if your team could emphasize this detail in the doc.

**Comment by lessw2020** [comment]
oh nice, I'm glad you caught that b/c I didn't follow the asterik with the very tiny "with sparsity" addendum when I looked a minute ago.  I don't believe they used to report it like that before - I believe they reported it as two sep numbers (dense and then sparse). 
Anyway, as you note, that does mean our current MFU numbers are correct.  
Will try and add the note that new Nvidia docs are reporting FLOPs with sparsity by default to help clarify this. 
Thanks again @LeoXinhaoLee!

**Comment by gameofdimension** [comment]
Is it possible to write code to measure the actual peak FLOPS (Floating Point Operations Per Second) under specific conditions?
