### ISSUE TITLE
Equivalence of  `sync_module_states` in fsdp2

### ISSUE THREAD

**Issue by qsh-zh** [pytorch/torchtitan#670]
For HSDP, does the full_shard API has a flag for automatically sync module buffers and parameters across replicas, or do users need to handle it manually?

**Comment by awgu** [comment]
Users need to handle it manually.

**Comment by awgu** [comment]
An example is in this [unit test](https://github.com/pytorch/pytorch/blob/419a7e197d2579e699c2e730902d197a27df8deb/test/distributed/_composable/fsdp/test_fully_shard_init.py#L987-L997).

**Comment by qsh-zh** [comment]
@awgu  thank you for your response.

Some related questions:

	•	When we shard a model within a shard group, the model weights are taken from rank 0, and the weights on other ranks are simply discarded, so they don’t matter.
	•	I’m wondering if `from torch.distributed.utils import _sync_module_states` can perform the same task. Would the `_broadcast_coalesced` function used by this method make it faster?

**Comment by awgu** [comment]
When broadcasting across ranks across different replicas, we only need to choose one rank as the source of truth; in that case, rank 0 suffices (or any other rank if you want).

I think `_sync_module_states` may work (and the `_broadcast_coalesced` may help communication efficiency). You just need to make sure you are operating on the `DTensor` local tensors in-place.
