### ISSUE TITLE
Question about FSDP2 + FP8 all gather

### ISSUE THREAD

**Issue by sbhavani** [pytorch/torchtitan#687]
Does FSDP2 work with both FP8 allgather and FP8 linear?

**Comment by awgu** [comment]
I think so. I think you have to use `FP8Linear` to use FP8 all-gather. cc: @weifengpy

**Comment by lessw2020** [comment]
Hi @sbhavani, Yes fsdp2 works with both. You can use fp8 linear by itself, and then add fp8 all gather on top. Of the combined speed gains, typically 80% comes from fp8 compute and 20% comes from the fp8 all gather.
We'll have a blog post next week showing fp8 gains at 512 gpu scale as well.
Hope this helps!

**Comment by tianyu-l** [comment]
You can find more details in https://discuss.pytorch.org/t/distributed-w-torchtitan-enabling-float8-all-gather-in-fsdp2/209323
