### ISSUE TITLE
consider - move to non parametric layernorm as default for llama models

### ISSUE THREAD

**Issue by lessw2020** [pytorch/torchtitan#85]
Per Olmo:
"Non-parametric layer norm. We use the non-parametric formulation of layer norm (Ba et al., [2016](https://arxiv.org/html/2402.00838v1#bib.bib3)) in which there is no affine transformation within the norm, i.e. no “adaptive gain” (or bias). We believe this was the safest option and it was also the fastest compared to the other variants we considered: parametric layer norm and RMSNorm (Zhang and Sennrich, [2019](https://arxiv.org/html/2402.00838v1#bib.bib70))."

safest and fastest seem like a nice win. 
I can make a PR to enable this, but adding as an issue for discussion.

**Comment by awgu** [comment]
I think we can close this since you have made the norm type configurable. Leaving RMSNorm as default seems okay to respect the original model definition.
